### ISSUE TITLE
Implement ENS setSubnodeOwner 

### ISSUE THREAD

**Issue by dportabella** [web3j/web3j#1248]
## Implement ENS setSubnodeOwner 

`web3js` allows creating ENS subdomains using the function `setSubnodeOwner`.
I see that this is not yet implemented in web3: 
  http://docs.web3j.io/ethereum_name_service/

Could this be implemented in web3?

https://web3js.readthedocs.io/en/v1.2.11/web3-eth-ens.html

**Comment by Mschnuff** [comment]
Hey, I am learning about web3j atm and would like to contribute to the Ethereum Java OSS project. Just to be sure I understand the issue correctly I ll rephrase it: In web3js there is a functionality that allows for setting ENS subdomains, in web3j that functionality doesnt exist. the goal of this issue is to also implement the same functionality in web3j?

**Comment by andrii-kl** [comment]
@dportabella  It was implemented for some time ago, you can try it out.
org.web3j.ens.contracts.generated.ENS#setSubnodeOwner
