### ISSUE TITLE
Besu 1.6 json-rpc error responses will be causing issues

### ISSUE THREAD

**Issue by iikirilov-wmt** [web3j/web3j#1272]
# _Issue_title_
read the title.

## _Issue_description_
Heads up: Besu will be aligning its JSON-RPC error numbers in the upcoming 1.6 release cycle in about a month from now -> hyperledger/besu#1305
Some of the besu specific code in Web3J depends on 4xx series responses for errors. Some of these errors will now come as HTTP 200 OK but with an error object in the JSON-RPC response. 4xx series responses will be reserved for when the RPC cannot be sensibly decoded.

## _Issue_context_
relaying msg from gitter

**Comment by shemnon** [comment]
So this is more likely a docs change than a needed code change.  Web3J will dutifully return the response object instead of throwing various forms of RuntimeException when a properly formatted call ends in an error (such as no block for a hash).  The error will be in the result object.

Classes in the `org.web3j.protocol.core.methods.response` and such may want to check for an error response and throw an exception before unwrapping the result.
