### ISSUE TITLE
Do you have any plans to update the web3j-android library?

### ISSUE THREAD

**Issue by sirano11** [web3j/web3j#1364]
web3J v4.8.4 has been updated to support ABI package bug fixes and tuple arrays. 
Do you have any plans to release an android library that supports this feature?

**Comment by sirano11** [comment]
@AlexandrouR Would you answer this question? :)

**Comment by AlexandrouR** [comment]
@sirano11 Hi, yes it is within our plans to update the Android library given that we have made some important additions to the main library however there are multiple projects and updates that we are working on at the moment and this is something that will be done passively. If you have any ideas feel free to do a pull request and I would be more than happy to collaborate on this.

**Comment by xrpdevs** [comment]
Is this possibly why when I'm passing Tuple3<List<BigInteger>, List<String>, List<String>> from my contract into my android app Im getting IndexOutOfBounds errors or similar? The First List<String> is ethereum address type, whereas the second is a Utf8String. It worked when I used bytes32 instead of String.

I've spent 2 days trying to work out if the problems I'm having are due to the library not being up to date with the spec or how the contract's bindings are being generated by web3j cli (which doesn't work in the latest version)

The contract works exactly as it should if I'm using the Remix IDE, so it's gotta be the library or the fact that I'm having to use an old version of web3j against a newer solc. <bangs head>
