### ISSUE TITLE
decode the return result: DynamicArray in DynamicStruct

### ISSUE THREAD

**Issue by greason** [web3j/web3j#1563]
## deal with the situation : DynamicArray in DynamicStruct
add a case in function of decodeDynamicParameterFromStruct

```
  // contract 
  struct ProposalInfo {
          uint256 proposalId;
          address creator;
          bytes32 title;
          bytes32[] optionTitles; 
  }

  function getProposalInfo(uint256 _proposalId) public 	view returns (ProposalInfo memory) {
          require(_proposalId < proposalInfo.length, "wrong input parameters");
	  return proposalInfo[_proposalId];
  }
```

```
  // java 
  public static class ProposalInfo extends DynamicStruct {
          public BigInteger proposalId;
          public String creator;
          public byte[] title;
          public List<byte[]> optionTitles;
  }
```

Just like this, so how should i decode the struct of return ,

suggestion:
TypeDecoder.java

```
private static <T extends Type> T decodeDynamicParameterFromStruct(
            final String input,
            final int parameterOffset,
            final int parameterLength,
            final Class<T> declaredField) {
        final String dynamicElementData =
                input.substring(parameterOffset, parameterOffset + parameterLength);

        final T value;
        if (DynamicStruct.class.isAssignableFrom(declaredField)) {
            value =
                    decodeDynamicStruct(
                            dynamicElementData, 64, TypeReference.create(declaredField));
        } else if (DynamicArray.class.isAssignableFrom(declaredField)) {
            value =
                    decodeDynamicArrayOfStruct(
                            dynamicElementData, 0, TypeReference.create(declaredField));
        } else {
            value = decode(dynamicElementData, declaredField);
        }
        return value;
}
```

Any one can help ?

**Comment by SweeXordious** [comment]
@greason Hello,
Sorry for the late reply.
I see this is an enhancement by adding that branch, however, I'm not sure if we need it.
So, please, can you open a new PR with this change? Then, add a test for it? And I will be glad to review
Thanks a lot for your help.

**Comment by jimmyneutront** [comment]
@greason , unfortunately your code won't work. If you are trying to decode a `DynamicArray` from a `DynamicStruct`, then the `declaredField` parameter passed to `decodeDynamicParameterFromStruct` is going to be a `DynamicArray.class` object. When you pass a `DynamicArray.class` object to `TypeReference.create`, the returned `TypeReference` object doesn't contain accurate information about the type of objects that are to stored in the `DynamicArray`, since there is no way for `TypeReference.create` to obtain this information given a `DynamicArray.class` object. As you can see in the screenshot, the type associated with the `DynamicArray` `TypeReference` is simply "T", instead of `DynamicBytes`, as it should be:
<img width="1440" alt="Screen Shot 2021-12-26 at 9 12 47 PM" src="https://user-images.githubusercontent.com/80171492/147427533-5dab2d93-7c40-4e1c-9773-2e6fb1615c2e.png">
Thus, when `decodeArrayElements` tries to determine the datatype held by the DynamicArray it is decoding using the passed `TypeReference`, it will not be able to do so and will throw an `ClassCastException` complaining that "class java.lang.Class cannot be cast to class java.lang.reflect.ParameterizedType".
@greason I believe we can get around this issue by creating our own raw transactions and decoding responses with our own custom-implemented decoder functions; I'll be doing this for [my own project](https://github.com/jimmyneutront/Commuto_Interface_Desktop) over the next week or so; perhaps looking at my work would help you create your own.
@SweeXordious I think that Web3J _**REALLY**_ needs this feature; as far as I can see, Web3J is currently incapable of decoding the responses of any function that returns a dynamic array. In order to fix it, we need to revamp the way that `TypeDecoder.decodeDynamicStructElements` figures out the data types contained by structs. Currently, it gets the list of parameter types from the constructor of the generated `DynamicStruct` wrapper around an actual Solidity `struct`. This design doesn't allow us to determine the datatypes held by `DynamicArray`s within the struct. Perhaps DynamicStruct should have a static abstract `getParameters` method, which returns a list of `TypeReference`s describing each datatype in the struct? This would require some work on the Web3J command line tools, specifically those for contract wrapper generation. If such a fix was implemented, it could also make resolving #1588 very simple. Please let me know what you think; I'm happy to get started on a fix.

**Comment by SweeXordious** [comment]
@jimmyneutront thanks a lot for your effort.
Yes please. Open a new PR containing the changes. Would be awesome.

**Comment by greason** [comment]
@SweeXordious Please check this, I add two test cases.

**Comment by kdziurdz** [comment]
@greason thank you for your input. We are struggling with this issue as well. I built your branch locally and decoding works as expected. Encoding doesn't work though. 
Will you add encoding to your PR to make it work back and forth?

Contract we use for testing:
```solidity
pragma solidity ^0.7.1;
pragma experimental ABIEncoderV2;

//pragma solidity 0.8.10;
//pragma abiencoder v2;

contract StructOfArraysTest {

    StructOfArrays structOfArrays;

    struct StructOfArrays {
        string[] names;
        uint256[] numbers;
        bool[] booleans;
    }

    constructor() {
        string[] memory names = new string[](2);
        names[0] = 'name1';
        names[1] = 'name2';

        uint256[] memory numbers = new uint256[](2);
        numbers[0] = 2137;
        numbers[1] = 7312;

        bool[] memory booleans = new bool[](2);
        booleans[0] = true;
        booleans[1] = false;

        structOfArrays = StructOfArrays(names, numbers, booleans);
    }


   // started to work thanks to this PR
    function getStruct() external view returns (StructOfArrays memory) {
        return structOfArrays;
    }

    // still need a fixPR
    function consumeStruct(StructOfArrays memory _structOfArrays) external {
        structOfArrays = _structOfArrays;
    }
}
```

**Comment by jimmyneutront** [comment]
@kdziurdz If you are having problems encoding, you may be running into the issue I described in #1588; I included a temporary fix in that issue as well. If my fix ends up helping, would you mind sharing the incorrect method signature generated by Web3J?

**Comment by greason** [comment]
@kdziurdz please help me to fix this before. That's why encoding doesn't work though.

How to get the item type of DynamicArray #getParameterizedTypeFromArray
```
@SuppressWarnings("unchecked")
static <T extends Type> Class<T> getParameterizedTypeFromArray(TypeReference typeReference)
        throws ClassNotFoundException {

    java.lang.reflect.Type type = typeReference.getType();
    if (!(type instanceof ParameterizedType)) {
        // how to get item type
            return (Class<T>) Utf8String.class;
//                return (Class<T>) Bytes32.class;
    }
    java.lang.reflect.Type[] typeArguments =
            ((ParameterizedType) type).getActualTypeArguments();

    String parameterizedTypeName = typeArguments[0].getTypeName();
    return (Class<T>) Class.forName(parameterizedTypeName);
}
```
