### ISSUE TITLE
Timeout on contract publication

### ISSUE THREAD

**Issue by tjdragon** [web3j/web3j#1609]
[#](url) Timeout on contract publication
Web3J timesout when publishing an ERC20 contract.

## Steps To Reproduce
Public an ERC20 contract - wait for 600 + seconds - timeout
However, the code returns a transaction hash:
Exception in thread "main" org.web3j.protocol.exceptions.TransactionException: Transaction receipt was not generated after 600 seconds for transaction: 0x47067dcd775d09d753f479685016b0df89ca846e2b26c74a9c0b808041df3711

### Expected behavior
Compared to Remix - we should get this tx hash very quickly
![tx](https://user-images.githubusercontent.com/24475889/150364284-f8e2eaee-9ca5-4680-8cb8-c844f1ab867f.PNG)

## Environment
_Describe the environment in which the issue occurs_
- Web3j version 4.8.9
- Java Open JDK 17
- Operating System Windows

## Additional context
Contracts are ultimately deployed: https://ropsten.etherscan.io/address/0x1996dcb50022c8e73c8ff1cf0e28adf73c47a7de
But no callbck from Web3J
Looks like something is wrong with polling - what is weird is that this used to work well before Christmas - same code.
Also noticed that polling is not configurable - and nothing is logged.
I wonder if this is link to massive increase in fees? TBC/TBD

Update on 21st Jan 2022: Now contracts do deploy in < 1 minute without issues. This problem persisted for a few weeks and was clearly related to Ropsten or Rinkeby.
However, I still think that polling timeout should be configurable and that feedback should be provided

**Comment by andrii-kl** [comment]
@tjdragon Web3j polling process has default configuration 40 attempts, with 15 sec sleepDuration (it's about 40 blocks or 600 sec). 
Also you can use custom configurations.You should init TransactionManadger/RawTransactionManager with your custom parameters 'attempts' and 'sleepDuration'. 

In my opinion, current problem is more about ropsten testnet. Very often the net is overload and fee becomes height.  That's why if you use an average fee, transaction could be stuck or it takes to long.
I would recommend increase transaction fee and take a look on other testnet (for example rinkeby).
