### ISSUE TITLE
eth_getFilterLogs error

### ISSUE THREAD

**Issue by zunpan** [web3j/web3j#1665]
# _Bug_title_
method “eth_getFilterLogs” use a wrong params when filtereid less than 0x10

## Steps To Reproduce
This is my filter code.
```java
EthFilter filter = new EthFilter(
                DefaultBlockParameterName.EARLIEST,
                DefaultBlockParameterName.LATEST,
                contractAddress);
        filter.addSingleTopic(EventEncoder.encode(VotingContract.RETURNVOTEID_EVENT));
        web3j.ethLogFlowable(filter)
                .subscribe(log -> {
                    logger.info("hash:"+log.getTransactionHash()+";"+"data:"+log.getData());
                }, error -> {
                    error.printStackTrace();
                });
```

### Expected behavior
nothing output

### Actual behavior
```java
java.lang.NullPointerException
	at org.web3j.protocol.core.filters.LogFilter.process(LogFilter.java:46)
	at org.web3j.protocol.core.filters.Filter.getInitialFilterLogs(Filter.java:119)
	at org.web3j.protocol.core.filters.Filter.run(Filter.java:69)
	at org.web3j.protocol.rx.JsonRpc2_0Rx.run(JsonRpc2_0Rx.java:89)
	at org.web3j.protocol.rx.JsonRpc2_0Rx.lambda$ethLogFlowable$2(JsonRpc2_0Rx.java:79)
	at io.reactivex.internal.operators.flowable.FlowableCreate.subscribeActual(FlowableCreate.java:71)
	at io.reactivex.Flowable.subscribe(Flowable.java:14935)
	at io.reactivex.Flowable.subscribe(Flowable.java:14872)
	at io.reactivex.Flowable.subscribe(Flowable.java:14791)
	at cn.edu.zjucst.listener.ContractListener.newVote(ContractListener.java:49)
	at cn.edu.zjucst.listener.ContractListener.run(ContractListener.java:39)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:795)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:785)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:333)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1311)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300)
	at cn.edu.zjucst.AppApplication.main(AppApplication.java:10)

```

## Environment
- Web3j version 4.8.7
- Java or Android version 1.8
- Operating System win10

## Additional context
- Logs
```
--> POST http://***.**.**.***:8545/

Content-Type: application/json; charset=utf-8

Content-Length: 241

{"jsonrpc":"2.0","method":"eth_newFilter","params":[{"topics":["0x4ad1269e844851cb096cb1288c24de3241625bc222823f047d80d388d31fe007"],"fromBlock":"earliest","toBlock":"latest","address":["0x3ad438090d6ca3c26f2e4c4c2e7833066b87e709"]}],"id":0}

--> END POST (241-byte body)

<-- 200 http://***.**.**.***:8545/ (159ms)

Content-Type: application/json

Content-Length: 39

{"id":0,"jsonrpc":"2.0","result":"0x1"}

<-- END HTTP (39-byte body)



--> POST http://***.**.**.***:8545/

Content-Type: application/json; charset=utf-8

Content-Length: 71

{"jsonrpc":"2.0","method":"eth_getFilterLogs","params":["0x01"],"id":1}

--> END POST (71-byte body)

<-- 200 http://***.**.**.***:8545/ (16ms)

Content-Type: application/json

Content-Length: 1051

{"id":1,"jsonrpc":"2.0","error":{"message":"filter not found","stack":"Error: filter not found\n    at EthereumApi.eth_getFilterLogs ......,"code":-32700}}

<-- END HTTP (1051-byte body)
```

modify request body `{"jsonrpc":"2.0","method":"eth_getFilterLogs","params":["0x01"],"id":1}` to `{"jsonrpc":"2.0","method":"eth_getFilterLogs","params":["0x1"],"id":1}` is working. 
I think the filterid in the'params' has a prefix 0 when filterid less than 0x10 causes the error.

When I repeat method 'eth_newFilter' until filterid equals 0x10, my code works.

**Comment by Xilis** [comment]
Observing same issue here! You might not run into the error depending on what you are using for your node.

I am seeing this error by using either the ganache docker image `trufflesuite/ganache:v7.0.4` or a hardhat node, but not while using the ganache gui.

The issue is that the parameter for the `eth_getFilterChanges` is padded with an extra 0. This results in an error returned by the node, which follows the [RPC](https://playground.open-rpc.org/?schemaUrl=https://raw.githubusercontent.com/ethereum/eth1.0-apis/assembled-spec/openrpc.json&uiSchema%5BappBar%5D%5Bui:splitView%5D=true&uiSchema%5BappBar%5D%5Bui:input%5D=false&uiSchema%5BappBar%5D%5Bui:examplesDropdown%5D=false) which uses the `^0x([1-9a-f]+[0-9a-f]*|0)$` regex for the single parameter for the `eth_getFilterLogs` call.

**Example running a java app against hardhat node**

`org.web3j.utils.Numeric#toHexStringWithPrefixSafe` returns (for example) `0x03`, and in the hardhat logs, we can see the following:
```
eth_getFilterChanges

  Errors encountered in param 0: Invalid value "0x03" supplied to : QUANTITY
```
manually setting this value to `0x3` through the debugger successfully works.

**Example using the open-rpc playground**

You can try it yourself [here](https://playground.open-rpc.org/?schemaUrl=https://raw.githubusercontent.com/ethereum/eth1.0-apis/assembled-spec/openrpc.json&uiSchema%5BappBar%5D%5Bui:splitView%5D=true&uiSchema%5BappBar%5D%5Bui:input%5D=false&uiSchema%5BappBar%5D%5Bui:examplesDropdown%5D=false). Scroll down to `eth_getFilterLogs`, click "TRY IT NOW" and set a param with a leading zero.

Request:
```
{
    "jsonrpc": "2.0",
    "method": "eth_getFilterLogs",
    "params": [
        "0x03"
    ],
    "id": 15
}
```
Response:
```
{
  "jsonrpc": "2.0",
  "id": 15,
  "error": {
    "code": -32602,
    "message": "Errors encountered in param 0: Invalid value \"0x03\" supplied to : QUANTITY"
  }
}
```
