### ISSUE TITLE
Better support for async non-blocking IO

### ISSUE THREAD

**Issue by evgenynacu** [web3j/web3j#171]
There is initial support for non-blocking IO, but it's not complete.
1. org.web3j.tx.Contract: do not use Async.run, but use sendAsync method from Request.
2. SolidityFunctionWrapperGenerator should use CompletableFuture for return values, not Future.
3. HttpService should implement sendAsync using non-blocking library.

**Comment by evgenynacu** [comment]
Also, why Future is used in some places? (Almost everywhere CompletableFuture can be used).
Is there a reason for that? (or is it just historically)
Thanks

**Comment by conor10** [comment]
@evgenynacu, thanks for your thoughts

1. I'm working on migrating the smart contract wrappers to use send() and sendAsync() to allow greater flexibility.
2. I want the generated smart contract code to be both Android and Java compatible which is why regular futures are used here.
3. Do you have an example of where you mean?

**Comment by evgenynacu** [comment]
@conor10 here is gist with async http service (from my code): https://gist.github.com/evgenynacu/650ceeeb6ea24ce1db7f50a7bdcb2538

take a look at sendAsync method. It's implemented using org.asynchttpclient.AsyncHttpClient (using nio)

Also I think Async.run should not be used in the project. Then async support will be full.

**Comment by conor10** [comment]
I'm going to stick to using OkHttp for the time being. I appreciate your thoughts on non-blocking libraries.
