### ISSUE TITLE
sha3 value is different from Solidity

### ISSUE THREAD

**Issue by KimiWu123** [web3j/web3j#194]
I'm trying to use Web3j to monitor my smart contract event. I found the first argument of topic is hashed event name. So, I'd like to hashed the event name with Web3j to map the event I want. However, I found the value is different.
Here is my case, 

    // my smart contract event
    EVWithdraw(address user ,uint256 amount ,bytes32 ticketID);

I hashed "EVWithdraw(address,uint256,bytes32)" in my smart contract,

    function getsha3(string func) public constant returns(bytes32) {
        return sha3("EVWithdraw(address,uint256,bytes32)"); 
    }
    // returns 0x953d0c27f84a9649b0e121099ffa9aeb7ed83e65eaed41d3627f895790c72d41

In my Java code, 

    String hashed = Hash.sha3("EVWithdraw(address,uint256,bytes32)");
    // returns 0x5e148119b535e6da59d359ccb21e1987190bf984ea6998cc09de3b3d056603bf

I use this [website](https://emn178.github.io/online-tools/keccak_256.html), it got the same result as solidity. 
Why are they different??? I traced sha3 class, it seems like use keccak256 also. Is it an encoding issue?

Any help would be appreciated.

**Comment by conor10** [comment]
The web3j sha3 function expects a hex encoded string value. If you convert the string to bytes first, you'll be good.

```java
Hash.sha3("EVWithdraw(address,uint256,bytes32)".getBytes(StandardCharsets.UTF_8))
```

**Comment by KimiWu123** [comment]
It works! Thank you!!

**Comment by TheRealDannz0r** [comment]
@KimiWu123 Hi, I'm doing something very similar -- would you mind telling me how you concatenated your parameters? I want to hash a concatenation of the types `address`, `uint256`, and `bytes32` both off-chain (Java) and on-chain (Solidity) two be the same.

I have tried two ways: using a string concatenating function and then use `keccak256(totalString)`, or take advantage of `keccak256(addressParam, uint256Param, bytes32Param)`.


Thanks,
Dan

**Comment by KimiWu123** [comment]
@TheRealDannz0r , Just like Cornor mentioned, you need to convert your _totalString_ to byte array and then do _keccak256_ on Java side.  

However, I have no idea how to concatenating those parameters in Solidity. You can search some type convert Solidity sample code on GitHub but I don't think it's a good idea to do that in Solidity. It's too complicated.

**Comment by TheRealDannz0r** [comment]
@KimiWu123 Thanks, I actually got it to work a few hours after posting. Instead of concatenating, I just take advantage of the tightly packed arguments and just passing them as separate arguments. Just have to make sure that the data types are exactly the same form off-chain as on Solidity. For example, a calling a function with parameter `uint32` and with the value `10` in Solidity is equivalent to `0000000a` off-chain. (Each hexadecimal number is represented by two characters/bits.)

**Comment by thomasmetta** [comment]
@TheRealDannz0r What do you mean by  passing them as separate arguments?

**Comment by TheRealDannz0r** [comment]
@thomasmetta What is known as "tightly packed" http://solidity.readthedocs.io/en/v0.4.21/units-and-global-variables.html#mathematical-and-cryptographic-functions. In the case above, `keccak256("ab", "c")` is equal to `keccak256("abc")`. But it is not always trivial to append different data types (e.g. not strings) since conversion is needed to a mutual data type (string). I would argue that this exposes you to loss of data.

My first comment in this thread is what I meant, instead of trying to append several parameters to one string (which are prone to errors and loss of data when converting due no such native method), I just tightly pack them.

**Tightly packed**: `keccak256(addressParam, uint256Param, bytes32Param)`
**Trying to concatenate them in some other way**: `keccak256(<addressParam +  uint256Param + bytes32Param>)`
