### ISSUE TITLE
Q: how to detect if transaction was reverted?

### ISSUE THREAD

**Issue by 4ntoine** [web3j/web3j#241]
How can i detect transaction is reverted? Let's say `require()` assertion fails in method body.

**Comment by tjanson** [comment]
I know it’s been a while – but perhaps for other readers: [This Ethereum StackExchange question](https://ethereum.stackexchange.com/questions/28889/what-is-the-exact-meaning-of-a-transactions-new-receipt-status-field) and the linked answer discus the `status` field.

In short: the value `1` means everything is fine. You can check this field in Web3j.

One gotcha: If you run your own chain and connect to a `geth` client (possibly others as well), the status field will only be present if `"byzantiumBlock": 0` is set in the genesis file, [as discussed here](https://github.com/ethereum/web3.js/issues/1138#issuecomment-364612414).

**Comment by codebazz** [comment]
@4ntoine  did you find any answer? A much needed query from me . Thanks

**Comment by codebazz** [comment]
@tjanson I understand your recommendation but my geth is already running in private so I can not modify the genesis file. Is there any other way like geth version etc?

**Comment by tjanson** [comment]
Heh, well, good question! There has to be, right? The actual Ethereum main net activated the Byzantium features somehow, the same way should be possible in any private net too.

Maybe make a backup, then try just modifying the genesis file and reinitialize – does that invalidate the existing chain data? Maybe it’ll just work.

Otherwise, [this StackExchange comment](https://ethereum.stackexchange.com/a/29412/39148) says you can modify the genesis file, start an additional peer, have them sync, then take the old one offline. Quite a lot of effort, but there you go.

This is definitely a question for the go-ethereum repo though – maybe check their Gitter / Discord. Chances are someone there knows the answer.

**Comment by codebazz** [comment]
Yeah. That would be interesting indeed. In fact, I was going to add an extra node very soon. Of course, I will try the whole process and let you know. :)  thanks for your suggestion 👍
