### ISSUE TITLE
Throwing OutOfMemoryError Failed to allocate bytes until OOM (due to fragmentation)

### ISSUE THREAD

**Issue by ameen192** [web3j/web3j#252]

**Comment by ameen192** [comment]
android:largeHeap="true"
android:hardwareAccelerated="false"
added both in manifest but then too i'm not able to load WalletUtils.credentials() in android, someone please let me know what the issue might be

![errorweb3](https://user-images.githubusercontent.com/30768364/33155864-37de4ce2-d01a-11e7-9c90-e70eb0c8ad39.jpeg)

**Comment by ilittle7** [comment]
How did you solve it？

**Comment by ameen192** [comment]
I extracted private key and passed instead

**Comment by nzkozar** [comment]
@ameen192 could you provide a code sample you used to extract private key and how you passed it to build credentials?

**Comment by subhodi** [comment]
@ameen192  How did you manage to overcome this error?
I am still facing this error.

**Comment by nzkozar** [comment]
@ameen192 I solved this by using tools like java keytool, to extract the private key and passed that directly to the credentials creation method.
Instead of using `Credentials credentials = WalletUtils.loadCredentials(password, walletFile);`
I used `Credentials credentials = Credentials.create(privateKeyString);`

Hope this helps
