### ISSUE TITLE
Relate events to event sender

### ISSUE THREAD

**Issue by guardiande** [web3j/web3j#270]
I have several instances of the same contract living on the blockchain. I want to pick up events by the event method provided by the wrapper classes. Those methods deliver event objects which have no relation to the underlying Log instance and thereby don't allow me to determine which instance sent the event.

Log contains the needed information (address) but not the event.

```
public class Log {
    private boolean removed;
    private String logIndex;
    private String transactionIndex;
    private String transactionHash;
    private String blockHash;
    private String blockNumber;
    private String address;
    private String data;
    private String type;
    private List<String> topics;
...
}
```

And since the event does not include the log index I cannot safely navigate from the event to the log instance.

Please provide the requested information or provide a way to derive the event directly from the log instance.

**Comment by guardiande** [comment]
Maybe even better would be to have the getXXXEvents(TransactionReceipt tr) filter on the events that were issued from the contract instance. AFAIK this would resemble the web3.js implementation.

**Comment by danieldietrich** [comment]
@conor10 In our current project (that should go to production in a few months) we need have the following use-case:

1. a singleton 'master' contract creates n 'child' contracts
2. both contract types, master and child, emit events
3. we want to relate events by the child contract address

The code generator creates contract wrappers that allow us to filter events by

* a TransactionReceipt
* start and end blocks

Both methods return a list of EventResponse objects. However, we are not able to navigate to the log that corresponds to an event. Especially the number of filtered events may be smaller than the number of logs. Therefore we can't assume that the index of an event corresponds to a log index.

But only the Log object contains the address of the contract that emitted the event.

**I would be happy to provide a pull request in order to make the Log available in the EventResponse. However, I need your design decision how this could be achieved.**

In order to preserve backward compatibility it could be done by adding new methods to a contract wrapper that return `List<MyEventReceipt>` instead of `List<MyEventResponse>` (informally):

```java
// the name is just a suggestion
class MyEventReceipt {
    Log log;
    MyEventResponse eventResponse;
}
```

In web3.js it is possible to access these kind of information having an event and I see several use-cases to do so.

What do you think?

**Comment by danieldietrich** [comment]
While working on this issue I realized that it was already solved on 14th Dec by @jaspervdbijl. See bedcfa0be40ab6ea95277f2cdd7eefac54227bf2.

Is it possible to create a new web3j release within the next weeks that contains this change?

**This issue can be closed.**

Many thanks!
