### ISSUE TITLE
Exception in generated contract method getXXXEvents if event contains indexed string 

### ISSUE THREAD

**Issue by AlainCo** [web3j/web3j#345]
Hi,
I'm trying to implement a contract which produce an event, with an indexed String field.

It fails with an exception about class cast exception in the generated code for "getXxxxEvents()" and "xxxEventObservable()"
when the indexed topic, instead of the non indexed data, is cast as a string while it is an Uint256 (the sha3 of the string is used as topic)
I've checked the topic can be generated this way, and match what is in the Log:
Uint256 urlHash = new Uint256(Numeric.toBigInt(Hash.sha3(myurl.getBytes("UTF-8"))));
String optTopicUrl = "0x" + TypeEncoder.encode(urlHash);

Here is my contract:
`pragma solidity ^0.4.10;
contract Notary {

	  event ProofOfExistence(uint256 indexed hash, string indexed url, uint date );

	  function notarizeExistence(uint256 hash,string url) {
	    ProofOfExistence(hash,url,block.timestamp);
	  }

}`

the failing code in the generated contract is in methods
`public List<ProofOfExistenceEventResponse> getProofOfExistenceEvents(TransactionReceipt transactionReceipt) ...
 public Observable<ProofOfExistenceEventResponse> proofOfExistenceEventObservable(DefaultBlockParameter startBlock, DefaultBlockParameter endBlock) ...`
at the line
`typedResponse.url = (String) eventValues.getIndexedValues().get(1).getValue();`

I've tried to read the string field in the non indexed array, but the method
`org.web3j.tx.Contract.staticExtractEventParameters(Event, Log)`
does not extract it from the Log object.

Note that as shown by issue #335 
it would be better if the shared code doing the conversion job 
`ProofOfExistenceEventResponse typedResponse = new ProofOfExistenceEventResponse();
typedResponse.hash = (BigInteger) eventValues.getIndexedValues().get(0).getValue();
typedResponse.url = (String) eventValues.getIndexedValues().get(1).getValue();
typedResponse.date = (BigInteger) eventValues.getNonIndexedValues().get(0).getValue();`

was separated and reusable, and reused by generated methods like "getProofOfExistenceEvents", "proofOfExistenceEventObservable"
and by a "Filtered" variant (that I've copied and edited because it is not generated, as explained in #335 )...

Hope this helps, and thanks for all.

**Comment by jchen86** [comment]
Apologies if my comment is irrelevant. I came across a similar problem with indexed strings in web3js. I've never used web3j but I thought it could be related. There's a good explanation [here](https://ethereum.stackexchange.com/questions/6840/indexed-event-with-string-not-getting-logged) about why indexed strings don't work in web3js. But in short, web3js cannot decode indexed string values since they are stored as hashed values in the topics. 

I'm guessing the hash value is passed to [`TypeDecoder.decodeUtf8String`](https://github.com/web3j/web3j/blob/36d5b6c79deec8786ce1724f623fc9f2639bdf96/abi/src/main/java/org/web3j/abi/TypeDecoder.java#L191) and the TypeDecoder is not able to decode the input.

**Comment by AlexandrouR** [comment]
is this still an issue ?

**Comment by AlexandrouR** [comment]
Issue closed due to inactivity.
