### ISSUE TITLE
transactionObservable doesn't work

### ISSUE THREAD

**Issue by liuzhijun23** [web3j/web3j#355]
I can use web3j to get balance and trasfer with my own ERC20 contract in private block chain of ethereum,and I can see that it work well.When I send a transaction and I want to observer the callback use transactionObservable,the code is like these:
              TransactionReceipt receipt = contract_love.transfer(addr1,value).send();
              web3.transactionObservable().subscribe(tx -> {
                    System.out.println("-------get transaction now-----");//this code not be called
               });
              Thread.sleep(5000000);
I can see the transfer trasaction work success in geth client,But I find that the code not be called ever.Anybody could give me some suggestion? I use geth 1.7.3,web3j use 3.2.0.

**Comment by iikirilov** [comment]
subscribe to the observable before making the transfer:

```
web3.transactionObservable().subscribe(...);
TransactionReceipt receipt = contract_love.transfer(addr1,value).send();
```

Also, I would use a CountDownLatch similar to the `run()` method in [this integration test](http://github.com/web3j/web3j/blob/master/integration-tests/src/test/java/org/web3j/protocol/core/ObservableIT.java) rather than an arbitrary `Thread.sleep()` call.

**Comment by iikirilov** [comment]
For future reference please use [gitter](https://gitter.im/web3j/web3j) for usage questions.
