### ISSUE TITLE
parity.personalNewAccountFromWallet(...) returns NullPointerException with valid arguments

### ISSUE THREAD

**Issue by beatrizsanchez** [web3j/web3j#72]
**Goal**
I am trying to create a wallet on a client that is not running a node and then create a new account on the blockchain from that wallet through `parity.personalNewAccountFromWallet(...)`.

**Context**
I can't find a way to access the credentials of an account created with `parity.personalNewAccount(...)` because `WalletUtils.loadCredentials(...)` will try loading the wallet from the remote client instead of the machine running the node. Therefore, I thought that the best way to create an account would be through the wallet. 

**What I am doing**
I am running `personalNewAccountFromWallet(...)` with non-null valid arguments (`WalletFile` and `Password`) yet the method throws a NullPointerException. My code is as follows:

```
ECKeyPair ecKeyPair = Keys.createEcKeyPair();
Credentials credentials = Credentials.create(ecKeyPair);
WalletFile wallet = Wallet.createLight(password, ecKeyPair);
ObjectMapper objectMapper = ObjectMapperFactory.getObjectMapper();
String output =  walletDir + "/" + wallet.getAddress() + ".json";
objectMapper.writeValue(new File(output), wallet);
parity.personalNewAccountFromWallet(wallet, password).send();
```

I need to know if this is an implementation error on my side or from the tools (web3j or ethereum)

Whether it was my mistake or not, I think the error message could be more helpful..

**Comment by conor10** [comment]
Hi @beatrizsanchez, it appears that the parity API has changed - this call is now named slightly differently from when I originally implemented it, which is why it is failing.

https://github.com/paritytech/parity/wiki/JSONRPC-parity_accounts-module#parity_newaccountfromwallet

You're welcome to submit a PR to rename this.

In terms of your code, the following is a more straight forwards implementation:

```java
String password = "password";
        String destDir = "/Users/Conor/tmp";
        ObjectMapper objectMapper = ObjectMapperFactory.getObjectMapper();

        String walletFileName = WalletUtils.generateNewWalletFile(password, new File(destDir), false);
        WalletFile walletFile = objectMapper.readValue(
                new File(destDir + File.separator + walletFileName), WalletFile.class);

        NewAccountIdentifier newAccountIdentifier = parity.personalNewAccountFromWallet(
                walletFile, password).send();
```

I've raised https://github.com/web3j/web3j/issues/74 for the main piece of work that needs to be done to support all of the revised calls properly.

**Comment by conor10** [comment]
Fixed by https://github.com/web3j/web3j/pull/147.
