### ISSUE TITLE
Web3j solidity generates : failure for abi of a library file

### ISSUE THREAD

**Issue by didier-durand** [web3j/web3j#777]
Solc can compile without error the file Keystore.sol file from ERC725 / ERC735 reference implementation by Mircea Pasoi : https://github.com/mirceapasoi/erc725-735/blob/master/contracts/KeyStore.sol

This compilation produces an ABI file just containing the 2 chars []

command 'web3j solidity generate' fails and says 'unable to parse ABI file'. 

This 2-char file is a valid ABI description.  So, the command should not fail, it should just not generate anything in Java and terminate properly.

**Comment by iikirilov** [comment]
As this is an interface, it is intended to be extended by some other contract. The smart contract wrapper generation fails because there is no `constructor`. This contract is not intended to be instantiated. Am I correct?

Maybe a better error should be thrown rather than completing successfully.

Alternatively, a default constructor should be generated.

Thoughts?

**Comment by didier-durand** [comment]
I would prefer to have a minimum Java class generated to be able to reflect on the Java side in our own code what truly happens on the Solidity side. Thanks!

**Comment by iikirilov** [comment]
Aah ok just read up on libraries - so you are looking to have simple smart contract wrapper with `deploy` and `load` methods for libraries?

**Comment by didier-durand** [comment]
yes, that's exactly what I am looking for so that libraries can be easily manipulated from Java.

**Comment by didier-durand** [comment]
yes, that's exactly what I am looking for so that libraries can be easily manipulated from Java.

**Comment by iikirilov** [comment]
@kostind thank you for clarifying. Agreed to take no further action as there is nothing to generate here.
