### ISSUE TITLE
Missing hex prefix for raw sign transaction

### ISSUE THREAD

**Issue by h2mch** [web3j/web3j#84]
According to the the documentation (https://docs.web3j.io/getting_started.html#transactions), a raw transaction should work like:
String hexValue = Hex.toHexString(signedMessage); EthSendTransaction ethSendTransaction = web3j.ethSendRawTransaction(hexValue).sendAsync().get();

Unfortunately the Hex.toHexString produces a hex value without the the 0x prefix, which is needed.

see my [pull request](https://github.com/web3j/web3j/pull/83)

**Comment by conor10** [comment]
Hi @h2mch, thanks for pointing this out.

This is an error in the documentation (which I have since corrected - see https://docs.web3j.io/getting_started.html#transactions)

The following integration test demonstrates the correct process:

https://github.com/web3j/web3j/blob/master/src/integration-test/java/org/web3j/protocol/scenarios/CreateRawTransactionIT.java#L32
