### ISSUE TITLE
Loading Contract and using function of contracts

### ISSUE THREAD

**Issue by nicail18** [web3j/web3j#846]
I have this error that when I deployed my contract and get the contract address so that I can load it and use some functions. 
When I try to run contract.isValid() after loading the contract. It always returns false. and I also can't use the functions properly. I am returning a string but it returns "web3j.protocol.core.RemoteCall@43fda40"

Can someone please help me

**Comment by tjanson** [comment]
* Regarding the function: You need to `send` the RemoteCall: `contract.someMethod().send()`.
* Regarding the `isValid`: Are you using a library? I may be wrong, but I think this is a bug and a false negative, i.e., not your fault and the contract is actually fine.

Rather than filing an issue, it’s better to use the [web3j Gitter channel](https://gitter.im/web3j/web3j). Questions get answered fairly quickly there.

**Comment by nicail18** [comment]
Okay thank you :)

**Comment by tjanson** [comment]
Sure. Is my guess right regarding the `isValid`: Is that contract using a library (`import { … } from …` in Solidity)? If so, it might be the same case as #644.

**Comment by nicail18** [comment]
No, my contract doesn't use any library

**Comment by nicail18** [comment]
No, my contract doesn't use any library

**Comment by nicail18** [comment]
I think this is still a bug

**Comment by tjanson** [comment]
Okay, then if possible use a debugger to inspect what’s happening in the isValid method call. Are you sure the generated Java wrapper is up-to-date? If you change and redeploy your Solidity contract, you need to regenerate the wrapper (so that the stored bytecode, which is used for isValid, matches exactly).

**Comment by nicail18** [comment]
Okay thank you :) I'll try it

**Comment by nicail18** [comment]
I use v3.4.0 because if I updated it to the latest version which is 4.1.0. When I try to generate a Java. There is ContractGasProvider error. When I searched that error, they say that it is still a bug.

**Comment by AlexandrouR** [comment]
Is this still an issue with the latest version of web3j ?
